spring.application.name=fitness-tracker

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/fitness_tracker
spring.datasource.username=fitness_user
spring.datasource.password=fitness_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.url=jdbc:postgresql://localhost:5432/fitness_tracker
spring.flyway.user=fitness_user
spring.flyway.password=fitness_pass
spring.flyway.enabled=true

# Server Configuration
server.port=8080
